eval$s=%w'n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"
<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i
+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eva
l$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[
1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=
""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o
<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)
*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1
]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+
l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";F
ile.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c
=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyod
aisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)
*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n"#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m")
.gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("r
uby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pa
ck("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;sy
stem("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split("
.")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);
o="";j=-1;0.upto(n*10*n*18-1){|i|;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpa
ck("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split("
.")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load
(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.
split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);
l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<
<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;p
uts(n);l1=""<<("#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eva
l$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[
1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0])
;e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].spli
t("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*                                                                                                                                                                                    
n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+                                                                                                                                                                                    
l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)                                                                                                                                                                                    
*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).re                                                                                                                                                                                    
verse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0])                                                                                                                                                                                    
;e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1                                                                                                                                                                                    
]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6                                                                                                                                                                                    
n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].spli                                                                                                                                                                                    
t("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"                                                                                                                                                                                    
*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z                                                                                                                                                                                    
+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("                                                                                                                                                                                    
m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)                                                                                                                                                                                    
?e[j+=1]:32);o<<#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=                                                                                                                                                                                    
""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.t                                                                                                                                                                                    
o_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eva                                                                                                                                                                                    
l$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o                                                                                                                                                                                    
<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"                                                                                                                                                                                    
%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[                                                                                                                                                                                    
1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)                                                                                                                                                                                    
*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).re                                                                                                                                                                                    
verse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0])                                                                                                                                                                                    
;e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1                                                                                                                                                                                    
]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6                                                                                                                                                                                    
n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].spli                                                                                                                                                                                    
t("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*                                                                                                                                                                                    
n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+                                                                                                                                                                                    
l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)                                                                                                                                                                                    
*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).re                                                                                                                                                                                    
verse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0])                                                                                                                                                                                    
;e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1                                                                                                                                                                                    
]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"
*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)
?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c
=(l1+s+l1+z+l1).reverse.to_i(2);b=#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpa
ck("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split("
.")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load
(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.
split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);
l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<
<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;p
uts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1)
{|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*
n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39
<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m")
.gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("r
uby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pa
ck("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;sy
stem("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split("
.")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);
o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.
split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$
s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*
6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n
)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<
("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").g#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+
l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";F
ile.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c
=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyod
aisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)
*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load
(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<                                                                                          <((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyod
aisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.                                                                                          split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;p
uts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6                                                                                          )*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marsh
al.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1)                                                                                          {|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#ge
nsokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[                                                                                          1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*
n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n",                                                                                          "");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n
*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39                                                                                          <<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"
6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].spli                                                                                          t("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n
*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsu                                                                                          b("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0
.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]                                                                                          =""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"
<<32<<"6n%d.rb"%#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=                                                                                          ""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.t
o_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eva                                                                                          l$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o
<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"                                                                                          %n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[
1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)                                                                                          *2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).re
verse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0])                                                                                          ;e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1
]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6                                                                                          n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].spli
t("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*                                                                                          n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+
l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)                                                                                          *2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).re
verse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0])                                                                                          ;e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1
]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6                                                                                          n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].spli
t("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"                                                                                          *n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z
+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("                                                                                          m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)
?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.                                                                                          open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);
l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c                                                                                          =(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load
(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<                                                                                          <((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyod
aisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.                                                                                          split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;p
uts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6                                                                                          )*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marsh
al.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1)                                                                                          {|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#ge
nsokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n)                                                                                          ;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to
_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"                                                                                          1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n"#n=$0.split("
.")[0].split("n"#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eva
l$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[
1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0])
;e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].spli
t("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)
*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1
]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"
*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)
?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c
=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyod
aisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6
)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#ge
nsokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"
1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n"#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pa
ck("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+
l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";F
ile.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c
=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyod
aisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)
*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load
(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.
split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marsh
al.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;#n=$0.split(".")[0].split("n")[
1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n
*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].spli
t("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0
.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""n=$0.split(".")[0
].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[#n=$0.split(".")[0].split("n"#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("1"*n*6*3)*2*n;s=""<<("1"*n*
6+"0"*n*6*2)*2*n;z=""<<("1"*n*6+"0"*n*6+"1"*n*6)*2*n;c=(l1+s+l1+z+l1).reverse.to_i(2);b=[Marshal.dump(c)].pack("m").gsub("\n","");m=Marshal.load(b.unpack("m")[0]);e="eval$s=%w"<<39<<($s+"#"+$s*n*9);o="";j=-1;0.upto(n*10*n*18-1){|i|;o<<((m[i]==1)?e[j+=1]:32);o<<((i%(18*n
)==18*n-1)?10:"");};o[-21,20]=""<<39<<".join#gensokyodaisu";File.open("6n%d.rb"%n,"w")do|f|;f.puts(o);end;system("ruby"<<32<<"6n%d.rb"%n);#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""#n=$0.split(".")[0].split("n")[1].to_i+1;puts(n);l1=""<<("'.join#gensokyodaisu
